mqtt:
  host: "127.0.0.1"
  port: 1883
  username: "username"
  password: "password"
  clientid: "test"
  prefix: "luminea2mqtt"
autodiscover:
  enabled: true
  topic: homeassistant
devices:
  - id: "sqy709956ply4inkx6ac87"
    key: "xxxxxxxxxxxxxxxx"
    friendlyname: "device1"
    refresh: 30
    reconnect: 10
    type: luminea_nx_4458
loglevel: "debug"
